"""first

Revision ID: 0784f93d98c4
Revises: 
Create Date: 2023-06-02 15:06:10.838790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0784f93d98c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('real_name', sa.String(), nullable=False),
    sa.Column('real_surname', sa.String(), nullable=False),
    sa.Column('vk_link', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_rounds', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('gameboard',
    sa.Column('userid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('enter_datetime', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_gameboard_field_id'), 'gameboard', ['field_id'], unique=False)
    op.create_index(op.f('ix_gameboard_userid'), 'gameboard', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameboard_userid'), table_name='gameboard')
    op.drop_index(op.f('ix_gameboard_field_id'), table_name='gameboard')
    op.drop_table('gameboard')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
