"""first2

Revision ID: 3cddb6874e5a
Revises: e4570f34acd1
Create Date: 2023-06-02 21:07:08.707854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cddb6874e5a'
down_revision = 'e4570f34acd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gameboard_user_id', table_name='gameboard')
    op.create_index(op.f('ix_gameboard_user_id'), 'gameboard', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameboard_user_id'), table_name='gameboard')
    op.create_index('ix_gameboard_user_id', 'gameboard', ['user_id'], unique=False)
    # ### end Alembic commands ###
