"""first2

Revision ID: 50910ebd8807
Revises: 0784f93d98c4
Create Date: 2023-06-02 20:15:58.189976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50910ebd8807'
down_revision = '0784f93d98c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboard', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_gameboard_userid', table_name='gameboard')
    op.create_index(op.f('ix_gameboard_user_id'), 'gameboard', ['user_id'], unique=False)
    op.drop_constraint('gameboard_userid_fkey', 'gameboard', type_='foreignkey')
    op.create_foreign_key(None, 'gameboard', 'user', ['user_id'], ['id'])
    op.drop_column('gameboard', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboard', sa.Column('userid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gameboard', type_='foreignkey')
    op.create_foreign_key('gameboard_userid_fkey', 'gameboard', 'user', ['userid'], ['id'])
    op.drop_index(op.f('ix_gameboard_user_id'), table_name='gameboard')
    op.create_index('ix_gameboard_userid', 'gameboard', ['userid'], unique=False)
    op.drop_column('gameboard', 'user_id')
    # ### end Alembic commands ###
