"""first2

Revision ID: e4570f34acd1
Revises: 50910ebd8807
Create Date: 2023-06-02 20:20:06.507894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4570f34acd1'
down_revision = '50910ebd8807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
